import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "@/app/css/globals.css";
import localFont from "next/font/local";
import Header from "@/components/shared/Header";
import DotBackground from "@/components/ui/DotBackground";
import ReactLenis from "lenis/react";

const LeagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});
const GlacialIndifference = localFont({
  src: [
    {
      path: "../fonts/GlacialIndifference-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GlacialIndifference-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Figora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root options={{ lerp: 0.06 }} />
      <body
        className={`${LeagueSpartan.variable} ${GlacialIndifference.className} bg-neutral relative overflow-clip antialiased`}
      >
        <DotBackground
          dotSize={0.09}
          gapX={1.5}
          gapY={1.5}
          dotColor="#0000002B"
          className="text-green absolute inset-0 left-1/2 h-full min-w-7xl -translate-x-1/2"
        />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
