import type { Metadata, Viewport } from "next";
import { League_Spartan, Darumadrop_One } from "next/font/google";
import "@/app/css/globals.css";
import localFont from "next/font/local";
import Header from "@/components/shared/Header";
import DotBackground from "@/components/ui/DotBackground";
import ReactLenis from "lenis/react";
import ThemeToggle from "@/components/shared/ThemeToggle";
import { themeInitScript } from "@/lib/theme-script";
import { cookies } from "next/headers";
import { backgroundGen } from "@/utils/backgroundGen";
import Footer from "@/components/shared/Footer";

const HeadingFont = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});
// const HeadingFont = Darumadrop_One({
//   variable: "--font-league-spartan",
//   weight: ["400"],
// });
const BodyFont = localFont({
  src: [
    {
      path: "../fonts/GlacialIndifference-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/GlacialIndifference-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Figora",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  // maximumScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dotBg = backgroundGen({
    dotSize: 3,
    gapX: 48,
    gapY: 48,
    dotColor: "rgba(0,0,0,0.1)",
  });
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme")?.value || null;
  return (
    <html
      lang="en"
      // className={theme && theme !== "light" ? theme : ""}
      data-theme={theme || "light"}
    >
      <head>
        {/* Theme is applied before React hydration */}
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <ReactLenis root options={{ lerp: 0.06 }} />
      <body
        style={{
          backgroundImage: dotBg,
          backgroundRepeat: "repeat",
          backgroundPositionX: "4px",
          // backgroundAttachment: "local",
        }}
        className={`${HeadingFont.variable} ${BodyFont.className} bg-neutral relative antialiased`}
      >
        <Header />
        {/* <ThemeToggle /> */}
        <main>{children}</main>
      </body>
      <Footer />
    </html>
  );
}
